### ISSUE TITLE
set gnutls handshake timeout

### ISSUE THREAD

**Issue by jduepmeier** [cmail-mta/cmail#59]
Is it possible to set the gnutls handshake timeout in the config file?

**Comment by cbdevnet** [comment]
Not currently, but adding this feature would be quite straightforward - though it would complicate the configuration file format.

I'm not entirely sure that the GnuTLS handshake timeout poses a problem with the current (GnuTLS default) value.

**Comment by jduepmeier** [comment]
My problem was not the handshake timeout. So I close this issue.
