### ISSUE TITLE
Document all the modules properly

### ISSUE THREAD

**Issue by jduepmeier** [cmail-mta/cmail#8]
docu docu docu !!!!

**Comment by cbdevnet** [comment]
Seems like you cant assign multiple people to issues :/

**Comment by cbdevnet** [comment]
Specifically: Create short README files in all module folders and properly document all parameters, setup procedures etc. on the webpage

**Comment by cbdevnet** [comment]
Things that need documentation:
- Routers (in/out): Probably should be done after the transition to path-based routing
- Forward variables: See above

**Comment by cbdevnet** [comment]
This is doing pretty well, more focus should now be placed on the website.
